# Generated by Django 4.0.5 on 2022-07-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='not specified', max_length=255),
        ),
    ]
