# Generated by Django 4.0.5 on 2022-07-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_given_name_customer_first_name'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO store_collection (title)
        VALUES ('collection1')
        """, """
        DELETE FROM store_collection
        WHERE title='collection1'
        """)
    ]
